# -*- coding: utf-8 -*-
"""模型和数据

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBACOv6NH61sP7FizhY0hWTOTm4yn475
"""

# model.py
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

def train_model():
    # 你的模型训练代码
    X = np.random.rand(100, 2)  # 100个样本，每个样本有2个特征
    y = np.random.randint(0, 2, 100)  # 100个标签，0或1
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    rf_model = RandomForestClassifier(n_estimators=100)
    rf_model.fit(X_train, y_train)

    svm_model = SVC(probability=True)
    svm_model.fit(X_train, y_train)

    np.savez("models_and_data.npz", rf_model=rf_model, svm_model=svm_model, X_test=X_test, y_test=y_test)

if __name__ == "__main__":
    train_model()