# -*- coding: utf-8 -*-
"""验证程序

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VreE-5S5lGXHBH-b9mXRSsKRCmabqsnL
"""

# validation.py
import numpy as np
from sklearn.metrics import roc_auc_score, confusion_matrix

def validate_model():
    data = np.load("models_and_data.npz", allow_pickle=True)
    rf_model = data['rf_model'].item()
    svm_model = data['svm_model'].item()
    X_test = data['X_test']
    y_test = data['y_test']

    y_pred_rf = rf_model.predict(X_test)
    y_pred_svm = svm_model.predict(X_test)

    def evaluate_model(y_true, y_pred, model_name):
        auc = roc_auc_score(y_true, y_pred)
        print(f"{model_name} AUC: {auc:.3f}")

        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
        sensitivity = tp / (tp + fn)
        specificity = tn / (tn + fp)
        print(f"{model_name} Sensitivity: {sensitivity:.3f}, Specificity: {specificity:.3f}")

    evaluate_model(y_test, y_pred_rf, "Random Forest")
    evaluate_model(y_test, y_pred_svm, "SVM")